name: IPFS deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn"
    - run: yarn install
      working-directory: client
    - run: yarn build --if-present
      working-directory: frontend
      env:
        NEXT_PUBLIC_MORALIS_APP_ID: ${{ secrets.NEXT_PUBLIC_MORALIS_APP_ID }}
        NEXT_PUBLIC_MORALIS_SERVER_URL: ${{ secrets.NEXT_PUBLIC_MORALIS_SERVER_URL }}
        NEXT_PUBLIC_WEB3_API_KEY: ${{ secrets.NEXT_PUBLIC_WEB3_API_KEY }}

  run-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        web3_api: 'https://api-staging.web3.storage'
        web3_token: ${{ secrets.NEXT_PUBLIC_WEB3_API_KEY }}
        path_to_add: 'frontend/.next'
        # test non default option
        include_hidden: true
